/* 
 * Regula FaceSDK Web API
 *
 * Regula FaceSDK Web API
 *
 * The version of the OpenAPI document: 3.2.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Regula.FaceSDK.WebClient.Client.OpenAPIDateConverter;

namespace Regula.FaceSDK.WebClient.Model
{
public class FaceQualityDetailsGroups
{
    
        
        public const int IMAGE_CHARACTERISTICS = 0;
    
        
        public const int HEAD_SIZE_AND_POSITIONS = 2;
    
        
        public const int FACE_QUALITY = 3;
    
        
        public const int EYES_CHARACTERISTICS = 4;
    
        
        public const int SHADOWS_AND_LIGHTNING = 5;
    
        
        public const int POSE_AND_EXPRESSION = 6;
    
        
        public const int HEAD_OCCLUSION = 7;
    
}
}
