/* 
 * Regula FaceSDK Web API
 *
 * Regula FaceSDK Web API
 *
 * The version of the OpenAPI document: 3.2.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Regula.FaceSDK.WebClient.Client.OpenAPIDateConverter;

namespace Regula.FaceSDK.WebClient.Model
{
public class FaceQualityConfigName
{
    
        
        public const string BACKGROUND_UNIFORMITY = "BackgroundUniformity";
    
        
        public const string BLUR_LEVEL = "BlurLevel";
    
        
        public const string CONTACT_LENSES = "ContactLenses";
    
        
        public const string DARK_GLASSES = "DarkGlasses";
    
        
        public const string EXPRESSION_LEVEL = "ExpressionLevel";
    
        
        public const string EYES_DISTANCE = "EyeLeftClosed";
    
        
        public const string EYES_RED = "EyeLeftCoveredWithHair";
    
        
        public const string EYE_LEFT_CLOSED = "EyeLeftOccluded";
    
        
        public const string EYE_LEFT_COVERED_WITH_HAIR = "EyeRightClosed";
    
        
        public const string EYE_LEFT_OCCLUDED = "EyeRightCoveredWithHair";
    
        
        public const string EYE_RIGHT_CLOSED = "EyeRightOccluded";
    
        
        public const string EYE_RIGHT_COVERED_WITH_HAIR = "EyesDistance";
    
        
        public const string EYE_RIGHT_OCCLUDED = "EyesRed";
    
        
        public const string FACE_DYNAMIC_RANGE = "FaceDynamicRange";
    
        
        public const string FACE_GLARE = "FaceGlare";
    
        
        public const string FACE_MID_POINT_HORIZONTAL_POSITION = "FaceMidPointHorizontalPosition";
    
        
        public const string FACE_MID_POINT_VERTICAL_POSITION = "FaceMidPointVerticalPosition";
    
        
        public const string FACE_OCCLUDED = "FaceOccluded";
    
        
        public const string FOREHEAD_COVERING = "ForeheadCovering";
    
        
        public const string FRAMES_TOO_HEAVY = "FramesTooHeavy";
    
        
        public const string HEAD_COVERING = "HeadCovering";
    
        
        public const string HEAD_HEIGHT_RATIO = "HeadHeightRatio";
    
        
        public const string HEAD_WIDTH_RATIO = "HeadWidthRatio";
    
        
        public const string IMAGE_CHANNELS_NUMBER = "ImageChannelsNumber";
    
        
        public const string IMAGE_HEIGHT = "ImageHeight";
    
        
        public const string IMAGE_WIDTH = "ImageWidth";
    
        
        public const string IMAGE_WIDTH_TO_HEIGHT = "ImageWidthToHeight";
    
        
        public const string MOUTH_OPEN = "MouthOpen";
    
        
        public const string NOISE_LEVEL = "NoiseLevel";
    
        
        public const string OFF_GAZE = "OffGaze";
    
        
        public const string OTHER_FACES = "OtherFaces";
    
        
        public const string PADDING_RATIO = "PaddingRatio";
    
        
        public const string PITCH = "Pitch";
    
        
        public const string REFLECTION_ON_GLASSES = "ReflectionOnGlasses";
    
        
        public const string ROLL = "Roll";
    
        
        public const string SHADOWS_ON_BACKGROUND = "ShadowsOnBackground";
    
        
        public const string SHADOWS_ON_FACE = "ShadowsOnFace";
    
        
        public const string SHOULDERS_POSE = "ShouldersPose";
    
        
        public const string SMILE = "Smile";
    
        
        public const string STRONG_MAKEUP = "StrongMakeup";
    
        
        public const string TOO_DARK = "TooDark";
    
        
        public const string TOO_LIGHT = "TooLight";
    
        
        public const string UNNATURAL_SKIN_TONE = "UnnaturalSkinTone";
    
        
        public const string YAW = "Yaw";
    
}
}
