/*
 * Regula FaceSDK Web API
 *
 * Regula FaceSDK Web API # Clients * [JavaScript](https://github.com/regulaforensics/FaceSDK-web-js-client) client for the browser and node.js based on axios * [Java](https://github.com/regulaforensics/FaceSDK-web-java-client) client compatible with jvm and android * [Python](https://github.com/regulaforensics/FaceSDK-web-python-client) 3.5+ client * [C#](https://github.com/regulaforensics/FaceSDK-web-csharp-client) client for .NET & .NET Core 
 *
 * The version of the OpenAPI document: 5.1.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Regula.FaceSDK.WebClient.Client.OpenAPIDateConverter;

namespace Regula.FaceSDK.WebClient.Model
{
    /// <summary>
    /// The processing status returned for each assessed quality characteristic.
    /// </summary>
    /// <value>The processing status returned for each assessed quality characteristic.</value>
    
    public enum FaceImageQualityStatus
    {
        /// <summary>
        /// Enum QUALITY_STATUS_FALSE for value: 0
        /// </summary>
        QUALITY_STATUS_FALSE = 0,

        /// <summary>
        /// Enum QUALITY_STATUS_TRUE for value: 1
        /// </summary>
        QUALITY_STATUS_TRUE = 1,

        /// <summary>
        /// Enum QUALITY_STATUS_UNDETERMINED for value: 2
        /// </summary>
        QUALITY_STATUS_UNDETERMINED = 2

    }

}
