/*
 * Regula FaceSDK Web API
 *
 * Regula FaceSDK Web API
 *
 * The version of the OpenAPI document: 3.2.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Regula.FaceSDK.WebClient.Client.OpenAPIDateConverter;

namespace Regula.FaceSDK.WebClient.Model
{
    /// <summary>
    /// Defines FaceImageQualityGroups
    /// </summary>
    
    public enum FaceImageQualityGroups
    {
        /// <summary>
        /// Enum IMAGE_CHARACTERISTICS for value: 1
        /// </summary>
        IMAGE_CHARACTERISTICS = 1,

        /// <summary>
        /// Enum HEAD_SIZE_AND_POSITIONS for value: 2
        /// </summary>
        HEAD_SIZE_AND_POSITIONS = 2,

        /// <summary>
        /// Enum FACE_QUALITY for value: 3
        /// </summary>
        FACE_QUALITY = 3,

        /// <summary>
        /// Enum EYES_CHARACTERISTICS for value: 4
        /// </summary>
        EYES_CHARACTERISTICS = 4,

        /// <summary>
        /// Enum SHADOWS_AND_LIGHTNING for value: 5
        /// </summary>
        SHADOWS_AND_LIGHTNING = 5,

        /// <summary>
        /// Enum POSE_AND_EXPRESSION for value: 6
        /// </summary>
        POSE_AND_EXPRESSION = 6,

        /// <summary>
        /// Enum HEAD_OCCLUSION for value: 8
        /// </summary>
        HEAD_OCCLUSION = 8

    }

}
