/* 
 * Regula FaceSDK Web API
 *
 * Regula FaceSDK Web API
 *
 * The version of the OpenAPI document: 3.2.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Regula.FaceSDK.WebClient.Client.OpenAPIDateConverter;

namespace Regula.FaceSDK.WebClient.Model
{
public class FaceQualityUnit
{
    
        
        public const string QUALITY_UNIT_PIXELS = "pixels";
    
        
        public const string QUALITY_UNIT_RELATIVE = "relative";
    
        
        public const string QUALITY_UNIT_PSC = "pcs";
    
        
        public const string QUALITY_UNIT_DEGREES = "degrees";
    
        
        public const string QUALITY_UNIT_PERCENT = "percent";
    
        
        public const string QUALITY_UNIT_BITS = "bits";
    
        
        public const string QUALITY_UNIT_QUANTITY = "quantity";
    
}
}
