/*
 * Regula Face SDK Web API
 *
 * <a href=\"https://regulaforensics.com/products/face-recognition-sdk/  \" target=\"_blank\">Regula Face SDK</a> is a cross-platform biometric verification solution for a digital identity verification process and image quality assurance. The SDK enables convenient and reliable face capture on the client side (mobile, web, and desktop) and further processing on the client or server side.   The Face SDK includes the following features:  * <a href=\"https://docs.regulaforensics.com/develop/face-sdk/overview/introduction/#face-detection\" target=\"_blank\">Face detection and image quality assessment</a> * <a href=\"https://docs.regulaforensics.com/develop/face-sdk/overview/introduction/#face-comparison-11\" target=\"_blank\">Face match (1:1)</a> * <a href=\"https://docs.regulaforensics.com/develop/face-sdk/overview/introduction/#face-identification-1n\" target=\"_blank\">Face search (1:N)</a> * <a href=\"https://docs.regulaforensics.com/develop/face-sdk/overview/introduction/#liveness-assessment\" target=\"_blank\">Liveness detection</a>  Here is the <a href=\"https://github.com/regulaforensics/FaceSDK-web-openapi  \" target=\"_blank\">OpenAPI specification on GitHub</a>.   ### Clients * [JavaScript](https://github.com/regulaforensics/FaceSDK-web-js-client) client for the browser and node.js based on axios * [Java](https://github.com/regulaforensics/FaceSDK-web-java-client) client compatible with jvm and android * [Python](https://github.com/regulaforensics/FaceSDK-web-python-client) 3.5+ client * [C#](https://github.com/regulaforensics/FaceSDK-web-csharp-client) client for .NET & .NET Core 
 *
 * The version of the OpenAPI document: 6.1.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Regula.FaceSDK.WebClient.Client.OpenAPIDateConverter;

namespace Regula.FaceSDK.WebClient.Model
{
    /// <summary>
    /// Face attributes.
    /// </summary>
    /// <value>Face attributes.</value>
    
    [JsonConverter(typeof(StringEnumConverter))]
    
    public enum FaceAttribute
    {
        /// <summary>
        /// Enum AGE for value: Age
        /// </summary>
        [EnumMember(Value = "Age")]
        AGE = 1,

        /// <summary>
        /// Enum EMOTION for value: Emotion
        /// </summary>
        [EnumMember(Value = "Emotion")]
        EMOTION = 2,

        /// <summary>
        /// Enum EYE_LEFT for value: EyeLeft
        /// </summary>
        [EnumMember(Value = "EyeLeft")]
        EYE_LEFT = 3,

        /// <summary>
        /// Enum EYE_RIGHT for value: EyeRight
        /// </summary>
        [EnumMember(Value = "EyeRight")]
        EYE_RIGHT = 4,

        /// <summary>
        /// Enum SMILE for value: Smile
        /// </summary>
        [EnumMember(Value = "Smile")]
        SMILE = 5,

        /// <summary>
        /// Enum GLASSES for value: Glasses
        /// </summary>
        [EnumMember(Value = "Glasses")]
        GLASSES = 6,

        /// <summary>
        /// Enum HEAD_COVERING for value: HeadCovering
        /// </summary>
        [EnumMember(Value = "HeadCovering")]
        HEAD_COVERING = 7,

        /// <summary>
        /// Enum FOREHEAD_COVERING for value: ForeheadCovering
        /// </summary>
        [EnumMember(Value = "ForeheadCovering")]
        FOREHEAD_COVERING = 8,

        /// <summary>
        /// Enum MOUTH for value: Mouth
        /// </summary>
        [EnumMember(Value = "Mouth")]
        MOUTH = 9,

        /// <summary>
        /// Enum MEDICAL_MASK for value: MedicalMask
        /// </summary>
        [EnumMember(Value = "MedicalMask")]
        MEDICAL_MASK = 10,

        /// <summary>
        /// Enum OCCLUSION for value: Occlusion
        /// </summary>
        [EnumMember(Value = "Occlusion")]
        OCCLUSION = 11,

        /// <summary>
        /// Enum STRONG_MAKEUP for value: StrongMakeup
        /// </summary>
        [EnumMember(Value = "StrongMakeup")]
        STRONG_MAKEUP = 12,

        /// <summary>
        /// Enum HEADPHONES for value: Headphones
        /// </summary>
        [EnumMember(Value = "Headphones")]
        HEADPHONES = 13

    }

}
