/*
 * Regula FaceSDK Web API
 *
 * Regula FaceSDK Web API # Clients * [JavaScript](https://github.com/regulaforensics/FaceSDK-web-js-client) client for the browser and node.js based on axios * [Java](https://github.com/regulaforensics/FaceSDK-web-java-client) client compatible with jvm and android * [Python](https://github.com/regulaforensics/FaceSDK-web-python-client) 3.5+ client * [C#](https://github.com/regulaforensics/FaceSDK-web-csharp-client) client for .NET & .NET Core 
 *
 * The version of the OpenAPI document: 4.1.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Regula.FaceSDK.WebClient.Client.OpenAPIDateConverter;

namespace Regula.FaceSDK.WebClient.Model
{
    /// <summary>
    /// The aspect ratio according to which face alignment is performed during face detection.
    /// </summary>
    /// <value>The aspect ratio according to which face alignment is performed during face detection.</value>
    
    public enum FaceAlignTypeQuality
    {
        /// <summary>
        /// Enum ALIGN_3x4 for value: 0
        /// </summary>
        ALIGN_3x4 = 0,

        /// <summary>
        /// Enum ALIGN_4x5 for value: 1
        /// </summary>
        ALIGN_4x5 = 1,

        /// <summary>
        /// Enum ALIGN_2x3 for value: 2
        /// </summary>
        ALIGN_2x3 = 2,

        /// <summary>
        /// Enum ALIGN_1x1 for value: 3
        /// </summary>
        ALIGN_1x1 = 3,

        /// <summary>
        /// Enum ALIGN_7x9 for value: 4
        /// </summary>
        ALIGN_7x9 = 4

    }

}
