/*
 * Regula Face SDK Web API
 *
 * <a href=\"https://regulaforensics.com/products/face-recognition-sdk/  \" target=\"_blank\">Regula Face SDK</a> is a cross-platform biometric verification solution for a digital identity verification process and image quality assurance. The SDK enables convenient and reliable face capture on the client side (mobile, web, and desktop) and further processing on the client or server side.   The Face SDK includes the following features:  * <a href=\"https://docs.regulaforensics.com/develop/face-sdk/overview/introduction/#face-detection\" target=\"_blank\">Face detection and image quality assessment</a> * <a href=\"https://docs.regulaforensics.com/develop/face-sdk/overview/introduction/#face-comparison-11\" target=\"_blank\">Face match (1:1)</a> * <a href=\"https://docs.regulaforensics.com/develop/face-sdk/overview/introduction/#face-identification-1n\" target=\"_blank\">Face search (1:N)</a> * <a href=\"https://docs.regulaforensics.com/develop/face-sdk/overview/introduction/#liveness-assessment\" target=\"_blank\">Liveness detection</a>  Here is the <a href=\"https://github.com/regulaforensics/FaceSDK-web-openapi  \" target=\"_blank\">OpenAPI specification on GitHub</a>.   ### Clients * [JavaScript](https://github.com/regulaforensics/FaceSDK-web-js-client) client for the browser and node.js based on axios * [Java](https://github.com/regulaforensics/FaceSDK-web-java-client) client compatible with jvm and android * [Python](https://github.com/regulaforensics/FaceSDK-web-python-client) 3.5+ client * [C#](https://github.com/regulaforensics/FaceSDK-web-csharp-client) client for .NET & .NET Core 
 *
 * The version of the OpenAPI document: 6.1.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Regula.FaceSDK.WebClient.Client.OpenAPIDateConverter;

namespace Regula.FaceSDK.WebClient.Model
{
    /// <summary>
    /// The filter condition, determines the type of comparison to be performed on the &#x60;name&#x60; values of the Person entity. &lt;br&gt;&lt;br&gt;When set to &#x60;in&#x60;, the &#x60;name&#x60; values of the Person should match any of the values specified in the &#x60;value&#x60; list. &lt;br&gt;&lt;br&gt;When set to &#x60;nin&#x60;, the &#x60;name&#x60; values of the Person should not match any of the values specified in the &#x60;value&#x60; list.
    /// </summary>
    /// <value>The filter condition, determines the type of comparison to be performed on the &#x60;name&#x60; values of the Person entity. &lt;br&gt;&lt;br&gt;When set to &#x60;in&#x60;, the &#x60;name&#x60; values of the Person should match any of the values specified in the &#x60;value&#x60; list. &lt;br&gt;&lt;br&gt;When set to &#x60;nin&#x60;, the &#x60;name&#x60; values of the Person should not match any of the values specified in the &#x60;value&#x60; list.</value>
    
    [JsonConverter(typeof(StringEnumConverter))]
    
    public enum FilterOp
    {
        /// <summary>
        /// Enum IN for value: in
        /// </summary>
        [EnumMember(Value = "in")]
        IN = 1,

        /// <summary>
        /// Enum NOT_IN for value: nin
        /// </summary>
        [EnumMember(Value = "nin")]
        NOT_IN = 2

    }

}
