/* 
 * Regula FaceSDK Web API
 *
 * Regula FaceSDK Web API
 *
 * The version of the OpenAPI document: 3.2.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Regula.FaceSDK.WebClient.Client.OpenAPIDateConverter;

namespace Regula.FaceSDK.WebClient.Model
{
    /// Face photo image source
public class ImageSource
{
    
        
        public const int DOCUMENT_PRINTED = 1;
    
        
        public const int DOCUMENT_RFID = 2;
    
        
        public const int LIVE = 3;
    
        
        public const int DOCUMENT_WITH_LIVE = 4;
    
        
        public const int EXTERNAL = 5;
    
}
}
