/*
 * Regula FaceSDK Web API
 *
 * Regula FaceSDK Web API # Clients * [JavaScript](https://github.com/regulaforensics/FaceSDK-web-js-client) client for the browser and node.js based on axios * [Java](https://github.com/regulaforensics/FaceSDK-web-java-client) client compatible with jvm and android * [Python](https://github.com/regulaforensics/FaceSDK-web-python-client) 3.5+ client * [C#](https://github.com/regulaforensics/FaceSDK-web-csharp-client) client for .NET & .NET Core 
 *
 * The version of the OpenAPI document: 6.1.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Regula.FaceSDK.WebClient.Client.OpenAPIDateConverter;

namespace Regula.FaceSDK.WebClient.Model
{
    /// <summary>
    /// MatchRequest
    /// </summary>
    [DataContract]
    public partial class MatchRequest :  IEquatable<MatchRequest>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="MatchRequest" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected MatchRequest() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="MatchRequest" /> class.
        /// </summary>
        /// <param name="tag">Session identificator..</param>
        /// <param name="thumbnails">Deprecated, use the &#x60;crop&#x60; field in &#x60;outputImageParams&#x60; instead. (default to false).</param>
        /// <param name="images">The array of all images included in the comparison. (required).</param>
        /// <param name="outputImageParams">outputImageParams.</param>
        public MatchRequest(string tag = default(string), bool thumbnails = false, List<MatchImage> images = default(List<MatchImage>), MatchRequestOutputImageParams outputImageParams = default(MatchRequestOutputImageParams))
        {
            // to ensure "images" is required (not null)
            if (images == null)
            {
                throw new InvalidDataException("images is a required property for MatchRequest and cannot be null");
            }
            else
            {
                this.Images = images;
            }

            this.Tag = tag;
            // use default value if no "thumbnails" provided
            if (thumbnails == null)
            {
                this.Thumbnails = false;
            }
            else
            {
                this.Thumbnails = thumbnails;
            }
            this.OutputImageParams = outputImageParams;
        }

        /// <summary>
        /// Session identificator.
        /// </summary>
        /// <value>Session identificator.</value>
        [DataMember(Name="tag", EmitDefaultValue=false)]
        public string Tag { get; set; }

        /// <summary>
        /// Deprecated, use the &#x60;crop&#x60; field in &#x60;outputImageParams&#x60; instead.
        /// </summary>
        /// <value>Deprecated, use the &#x60;crop&#x60; field in &#x60;outputImageParams&#x60; instead.</value>
        [DataMember(Name="thumbnails", EmitDefaultValue=false)]
        [Obsolete]
        public bool Thumbnails { get; set; }

        /// <summary>
        /// The array of all images included in the comparison.
        /// </summary>
        /// <value>The array of all images included in the comparison.</value>
        [DataMember(Name="images", EmitDefaultValue=true)]
        public List<MatchImage> Images { get; set; }

        /// <summary>
        /// Gets or Sets OutputImageParams
        /// </summary>
        [DataMember(Name="outputImageParams", EmitDefaultValue=false)]
        public MatchRequestOutputImageParams OutputImageParams { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class MatchRequest {\n");
            sb.Append("  Tag: ").Append(Tag).Append("\n");
            sb.Append("  Thumbnails: ").Append(Thumbnails).Append("\n");
            sb.Append("  Images: ").Append(Images).Append("\n");
            sb.Append("  OutputImageParams: ").Append(OutputImageParams).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as MatchRequest);
        }

        /// <summary>
        /// Returns true if MatchRequest instances are equal
        /// </summary>
        /// <param name="input">Instance of MatchRequest to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(MatchRequest input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Tag == input.Tag ||
                    (this.Tag != null &&
                    this.Tag.Equals(input.Tag))
                ) && 
                (
                    this.Thumbnails == input.Thumbnails ||
                    (this.Thumbnails != null &&
                    this.Thumbnails.Equals(input.Thumbnails))
                ) && 
                (
                    this.Images == input.Images ||
                    this.Images != null &&
                    input.Images != null &&
                    this.Images.SequenceEqual(input.Images)
                ) && 
                (
                    this.OutputImageParams == input.OutputImageParams ||
                    (this.OutputImageParams != null &&
                    this.OutputImageParams.Equals(input.OutputImageParams))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Tag != null)
                    hashCode = hashCode * 59 + this.Tag.GetHashCode();
                if (this.Thumbnails != null)
                    hashCode = hashCode * 59 + this.Thumbnails.GetHashCode();
                if (this.Images != null)
                    hashCode = hashCode * 59 + this.Images.GetHashCode();
                if (this.OutputImageParams != null)
                    hashCode = hashCode * 59 + this.OutputImageParams.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
