/*
 * Regula FaceSDK Web API
 *
 * [Download OpenAPI specification](https://github.com/regulaforensics/FaceSDK-web-openapi) ### Clients * [JavaScript](https://github.com/regulaforensics/FaceSDK-web-js-client) client for the browser and node.js based on axios * [Java](https://github.com/regulaforensics/FaceSDK-web-java-client) client compatible with jvm and android * [Python](https://github.com/regulaforensics/FaceSDK-web-python-client) 3.5+ client * [C#](https://github.com/regulaforensics/FaceSDK-web-csharp-client) client for .NET & .NET Core 
 *
 * The version of the OpenAPI document: 6.1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Regula.FaceSDK.WebClient.Client.OpenAPIDateConverter;

namespace Regula.FaceSDK.WebClient.Model
{
    /// <summary>
    /// MatchImageDetection
    /// </summary>
    [DataContract(Name = "MatchImageDetection")]
    public partial class MatchImageDetection : IValidatableObject
    {

        /// <summary>
        /// Gets or Sets Status
        /// </summary>
        [DataMember(Name = "status", IsRequired = true, EmitDefaultValue = true)]
        public FaceSDKResultCode Status { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="MatchImageDetection" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected MatchImageDetection() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="MatchImageDetection" /> class.
        /// </summary>
        /// <param name="faces">The array of detected faces..</param>
        /// <param name="imageIndex">The image index number. Can be given; if not given, the index numbers are set automatically starting from 0. All index numbers must be whole and unique—not repeated. (required).</param>
        /// <param name="status">status (required).</param>
        public MatchImageDetection(List<DetectionFace> faces = default(List<DetectionFace>), int imageIndex = default(int), FaceSDKResultCode status = default(FaceSDKResultCode))
        {
            this.ImageIndex = imageIndex;
            this.Status = status;
            this.Faces = faces;
        }

        /// <summary>
        /// The array of detected faces.
        /// </summary>
        /// <value>The array of detected faces.</value>
        [DataMember(Name = "faces", EmitDefaultValue = false)]
        public List<DetectionFace> Faces { get; set; }

        /// <summary>
        /// The image index number. Can be given; if not given, the index numbers are set automatically starting from 0. All index numbers must be whole and unique—not repeated.
        /// </summary>
        /// <value>The image index number. Can be given; if not given, the index numbers are set automatically starting from 0. All index numbers must be whole and unique—not repeated.</value>
        [DataMember(Name = "imageIndex", IsRequired = true, EmitDefaultValue = true)]
        public int ImageIndex { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class MatchImageDetection {\n");
            sb.Append("  Faces: ").Append(Faces).Append("\n");
            sb.Append("  ImageIndex: ").Append(ImageIndex).Append("\n");
            sb.Append("  Status: ").Append(Status).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
