/*
 * Regula Face SDK Web API
 *
 * <a href=\"https://regulaforensics.com/products/face-recognition-sdk/  \" target=\"_blank\">Regula Face SDK</a> is a cross-platform biometric verification solution for a digital identity verification process and image quality assurance. The SDK enables convenient and reliable face capture on the client side (mobile, web, and desktop) and further processing on the client or server side.   The Face SDK includes the following features:  * <a href=\"https://docs.regulaforensics.com/develop/face-sdk/overview/introduction/#face-detection\" target=\"_blank\">Face detection and image quality assessment</a> * <a href=\"https://docs.regulaforensics.com/develop/face-sdk/overview/introduction/#face-comparison-11\" target=\"_blank\">Face match (1:1)</a> * <a href=\"https://docs.regulaforensics.com/develop/face-sdk/overview/introduction/#face-identification-1n\" target=\"_blank\">Face search (1:N)</a> * <a href=\"https://docs.regulaforensics.com/develop/face-sdk/overview/introduction/#liveness-assessment\" target=\"_blank\">Liveness detection</a>  Here is the <a href=\"https://github.com/regulaforensics/FaceSDK-web-openapi  \" target=\"_blank\">OpenAPI specification on GitHub</a>.   ### Clients * [JavaScript](https://github.com/regulaforensics/FaceSDK-web-js-client) client for the browser and node.js based on axios * [Java](https://github.com/regulaforensics/FaceSDK-web-java-client) client compatible with jvm and android * [Python](https://github.com/regulaforensics/FaceSDK-web-python-client) 3.5+ client * [C#](https://github.com/regulaforensics/FaceSDK-web-csharp-client) client for .NET & .NET Core 
 *
 * The version of the OpenAPI document: 7.2.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Net.Mime;
using Regula.FaceSDK.WebClient.Client;
using Regula.FaceSDK.WebClient.Model;

namespace Regula.FaceSDK.WebClient.Api
{

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IHealthcheckApiSync : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// Server healthcheck
        /// </summary>
        /// <remarks>
        /// The &#x60;/api/healthz&#x60; endpoint performs a server health check, providing details such as the application name, license ID, serial number, validity, and product version. &lt;br&gt;&lt;br&gt;Comprehensive information about service diagnostics is available on the [Monitoring page](https://docs.regulaforensics.com/develop/face-sdk/web-service/administration/monitoring/).
        /// </remarks>
        /// <exception cref="Regula.FaceSDK.WebClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xRequestID">Request header label. (optional)</param>
        /// <returns>DeviceInfo</returns>
        DeviceInfo Healthz(string? xRequestID = default);

        /// <summary>
        /// Server healthcheck
        /// </summary>
        /// <remarks>
        /// The &#x60;/api/healthz&#x60; endpoint performs a server health check, providing details such as the application name, license ID, serial number, validity, and product version. &lt;br&gt;&lt;br&gt;Comprehensive information about service diagnostics is available on the [Monitoring page](https://docs.regulaforensics.com/develop/face-sdk/web-service/administration/monitoring/).
        /// </remarks>
        /// <exception cref="Regula.FaceSDK.WebClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xRequestID">Request header label. (optional)</param>
        /// <returns>ApiResponse of DeviceInfo</returns>
        ApiResponse<DeviceInfo> HealthzWithHttpInfo(string? xRequestID = default);
        /// <summary>
        /// License healthcheck
        /// </summary>
        /// <remarks>
        /// The &#x60;/api/readyz&#x60; endpoint checks the license&#39;s health to determine if the application is ready for operation. It validates the license and returns a response indicating whether the license is valid (&#x60;200&#x60;) or invalid (&#x60;400&#x60;).
        /// </remarks>
        /// <exception cref="Regula.FaceSDK.WebClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xRequestID">Request header label. (optional)</param>
        /// <returns></returns>
        void Readyz(string? xRequestID = default);

        /// <summary>
        /// License healthcheck
        /// </summary>
        /// <remarks>
        /// The &#x60;/api/readyz&#x60; endpoint checks the license&#39;s health to determine if the application is ready for operation. It validates the license and returns a response indicating whether the license is valid (&#x60;200&#x60;) or invalid (&#x60;400&#x60;).
        /// </remarks>
        /// <exception cref="Regula.FaceSDK.WebClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xRequestID">Request header label. (optional)</param>
        /// <returns>ApiResponse of Object(void)</returns>
        ApiResponse<Object> ReadyzWithHttpInfo(string? xRequestID = default);
        #endregion Synchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IHealthcheckApiAsync : IApiAccessor
    {
        #region Asynchronous Operations
        /// <summary>
        /// Server healthcheck
        /// </summary>
        /// <remarks>
        /// The &#x60;/api/healthz&#x60; endpoint performs a server health check, providing details such as the application name, license ID, serial number, validity, and product version. &lt;br&gt;&lt;br&gt;Comprehensive information about service diagnostics is available on the [Monitoring page](https://docs.regulaforensics.com/develop/face-sdk/web-service/administration/monitoring/).
        /// </remarks>
        /// <exception cref="Regula.FaceSDK.WebClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xRequestID">Request header label. (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of DeviceInfo</returns>
        System.Threading.Tasks.Task<DeviceInfo> HealthzAsync(string? xRequestID = default, System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// Server healthcheck
        /// </summary>
        /// <remarks>
        /// The &#x60;/api/healthz&#x60; endpoint performs a server health check, providing details such as the application name, license ID, serial number, validity, and product version. &lt;br&gt;&lt;br&gt;Comprehensive information about service diagnostics is available on the [Monitoring page](https://docs.regulaforensics.com/develop/face-sdk/web-service/administration/monitoring/).
        /// </remarks>
        /// <exception cref="Regula.FaceSDK.WebClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xRequestID">Request header label. (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (DeviceInfo)</returns>
        System.Threading.Tasks.Task<ApiResponse<DeviceInfo>> HealthzWithHttpInfoAsync(string? xRequestID = default, System.Threading.CancellationToken cancellationToken = default);
        /// <summary>
        /// License healthcheck
        /// </summary>
        /// <remarks>
        /// The &#x60;/api/readyz&#x60; endpoint checks the license&#39;s health to determine if the application is ready for operation. It validates the license and returns a response indicating whether the license is valid (&#x60;200&#x60;) or invalid (&#x60;400&#x60;).
        /// </remarks>
        /// <exception cref="Regula.FaceSDK.WebClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xRequestID">Request header label. (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of void</returns>
        System.Threading.Tasks.Task ReadyzAsync(string? xRequestID = default, System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// License healthcheck
        /// </summary>
        /// <remarks>
        /// The &#x60;/api/readyz&#x60; endpoint checks the license&#39;s health to determine if the application is ready for operation. It validates the license and returns a response indicating whether the license is valid (&#x60;200&#x60;) or invalid (&#x60;400&#x60;).
        /// </remarks>
        /// <exception cref="Regula.FaceSDK.WebClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xRequestID">Request header label. (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse</returns>
        System.Threading.Tasks.Task<ApiResponse<Object>> ReadyzWithHttpInfoAsync(string? xRequestID = default, System.Threading.CancellationToken cancellationToken = default);
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IHealthcheckApi : IHealthcheckApiSync, IHealthcheckApiAsync
    {

    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class HealthcheckApi : IDisposable, IHealthcheckApi
    {
        private Regula.FaceSDK.WebClient.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="HealthcheckApi"/> class.
        /// **IMPORTANT** This will also create an instance of HttpClient, which is less than ideal.
        /// It's better to reuse the <see href="https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests#issues-with-the-original-httpclient-class-available-in-net">HttpClient and HttpClientHandler</see>.
        /// </summary>
        /// <returns></returns>
        public HealthcheckApi() : this((string)null)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="HealthcheckApi"/> class.
        /// **IMPORTANT** This will also create an instance of HttpClient, which is less than ideal.
        /// It's better to reuse the <see href="https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests#issues-with-the-original-httpclient-class-available-in-net">HttpClient and HttpClientHandler</see>.
        /// </summary>
        /// <param name="basePath">The target service's base path in URL format.</param>
        /// <exception cref="ArgumentException"></exception>
        /// <returns></returns>
        public HealthcheckApi(string basePath)
        {
            this.Configuration = Regula.FaceSDK.WebClient.Client.Configuration.MergeConfigurations(
                Regula.FaceSDK.WebClient.Client.GlobalConfiguration.Instance,
                new Regula.FaceSDK.WebClient.Client.Configuration { BasePath = basePath }
            );
            this.ApiClient = new Regula.FaceSDK.WebClient.Client.ApiClient(this.Configuration.BasePath);
            this.Client =  this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            this.ExceptionFactory = Regula.FaceSDK.WebClient.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="HealthcheckApi"/> class using Configuration object.
        /// **IMPORTANT** This will also create an instance of HttpClient, which is less than ideal.
        /// It's better to reuse the <see href="https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests#issues-with-the-original-httpclient-class-available-in-net">HttpClient and HttpClientHandler</see>.
        /// </summary>
        /// <param name="configuration">An instance of Configuration.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <returns></returns>
        public HealthcheckApi(Regula.FaceSDK.WebClient.Client.Configuration configuration)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Configuration = Regula.FaceSDK.WebClient.Client.Configuration.MergeConfigurations(
                Regula.FaceSDK.WebClient.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.ApiClient = new Regula.FaceSDK.WebClient.Client.ApiClient(this.Configuration.BasePath);
            this.Client = this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            ExceptionFactory = Regula.FaceSDK.WebClient.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="HealthcheckApi"/> class.
        /// </summary>
        /// <param name="client">An instance of HttpClient.</param>
        /// <param name="handler">An optional instance of HttpClientHandler that is used by HttpClient.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <returns></returns>
        /// <remarks>
        /// Some configuration settings will not be applied without passing an HttpClientHandler.
        /// The features affected are: Setting and Retrieving Cookies, Client Certificates, Proxy settings.
        /// </remarks>
        public HealthcheckApi(HttpClient client, HttpClientHandler handler = null) : this(client, (string)null, handler)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="HealthcheckApi"/> class.
        /// </summary>
        /// <param name="client">An instance of HttpClient.</param>
        /// <param name="basePath">The target service's base path in URL format.</param>
        /// <param name="handler">An optional instance of HttpClientHandler that is used by HttpClient.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <exception cref="ArgumentException"></exception>
        /// <returns></returns>
        /// <remarks>
        /// Some configuration settings will not be applied without passing an HttpClientHandler.
        /// The features affected are: Setting and Retrieving Cookies, Client Certificates, Proxy settings.
        /// </remarks>
        public HealthcheckApi(HttpClient client, string basePath, HttpClientHandler handler = null)
        {
            if (client == null) throw new ArgumentNullException("client");

            this.Configuration = Regula.FaceSDK.WebClient.Client.Configuration.MergeConfigurations(
                Regula.FaceSDK.WebClient.Client.GlobalConfiguration.Instance,
                new Regula.FaceSDK.WebClient.Client.Configuration { BasePath = basePath }
            );
            this.ApiClient = new Regula.FaceSDK.WebClient.Client.ApiClient(client, this.Configuration.BasePath, handler);
            this.Client =  this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            this.ExceptionFactory = Regula.FaceSDK.WebClient.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="HealthcheckApi"/> class using Configuration object.
        /// </summary>
        /// <param name="client">An instance of HttpClient.</param>
        /// <param name="configuration">An instance of Configuration.</param>
        /// <param name="handler">An optional instance of HttpClientHandler that is used by HttpClient.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <returns></returns>
        /// <remarks>
        /// Some configuration settings will not be applied without passing an HttpClientHandler.
        /// The features affected are: Setting and Retrieving Cookies, Client Certificates, Proxy settings.
        /// </remarks>
        public HealthcheckApi(HttpClient client, Regula.FaceSDK.WebClient.Client.Configuration configuration, HttpClientHandler handler = null)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");
            if (client == null) throw new ArgumentNullException("client");

            this.Configuration = Regula.FaceSDK.WebClient.Client.Configuration.MergeConfigurations(
                Regula.FaceSDK.WebClient.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.ApiClient = new Regula.FaceSDK.WebClient.Client.ApiClient(client, this.Configuration.BasePath, handler);
            this.Client = this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            ExceptionFactory = Regula.FaceSDK.WebClient.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="HealthcheckApi"/> class
        /// using a Configuration object and client instance.
        /// </summary>
        /// <param name="client">The client interface for synchronous API access.</param>
        /// <param name="asyncClient">The client interface for asynchronous API access.</param>
        /// <param name="configuration">The configuration object.</param>
        /// <exception cref="ArgumentNullException"></exception>
        public HealthcheckApi(Regula.FaceSDK.WebClient.Client.ISynchronousClient client, Regula.FaceSDK.WebClient.Client.IAsynchronousClient asyncClient, Regula.FaceSDK.WebClient.Client.IReadableConfiguration configuration)
        {
            if (client == null) throw new ArgumentNullException("client");
            if (asyncClient == null) throw new ArgumentNullException("asyncClient");
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Client = client;
            this.AsynchronousClient = asyncClient;
            this.Configuration = configuration;
            this.ExceptionFactory = Regula.FaceSDK.WebClient.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Disposes resources if they were created by us
        /// </summary>
        public void Dispose()
        {
            this.ApiClient?.Dispose();
        }

        /// <summary>
        /// Holds the ApiClient if created
        /// </summary>
        public Regula.FaceSDK.WebClient.Client.ApiClient ApiClient { get; set; } = null;

        /// <summary>
        /// The client for accessing this underlying API asynchronously.
        /// </summary>
        public Regula.FaceSDK.WebClient.Client.IAsynchronousClient AsynchronousClient { get; set; }

        /// <summary>
        /// The client for accessing this underlying API synchronously.
        /// </summary>
        public Regula.FaceSDK.WebClient.Client.ISynchronousClient Client { get; set; }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public string GetBasePath()
        {
            return this.Configuration.BasePath;
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public Regula.FaceSDK.WebClient.Client.IReadableConfiguration Configuration { get; set; }

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public Regula.FaceSDK.WebClient.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Server healthcheck The &#x60;/api/healthz&#x60; endpoint performs a server health check, providing details such as the application name, license ID, serial number, validity, and product version. &lt;br&gt;&lt;br&gt;Comprehensive information about service diagnostics is available on the [Monitoring page](https://docs.regulaforensics.com/develop/face-sdk/web-service/administration/monitoring/).
        /// </summary>
        /// <exception cref="Regula.FaceSDK.WebClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xRequestID">Request header label. (optional)</param>
        /// <returns>DeviceInfo</returns>
        public DeviceInfo Healthz(string? xRequestID = default)
        {
            Regula.FaceSDK.WebClient.Client.ApiResponse<DeviceInfo> localVarResponse = HealthzWithHttpInfo(xRequestID);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Server healthcheck The &#x60;/api/healthz&#x60; endpoint performs a server health check, providing details such as the application name, license ID, serial number, validity, and product version. &lt;br&gt;&lt;br&gt;Comprehensive information about service diagnostics is available on the [Monitoring page](https://docs.regulaforensics.com/develop/face-sdk/web-service/administration/monitoring/).
        /// </summary>
        /// <exception cref="Regula.FaceSDK.WebClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xRequestID">Request header label. (optional)</param>
        /// <returns>ApiResponse of DeviceInfo</returns>
        public Regula.FaceSDK.WebClient.Client.ApiResponse<DeviceInfo> HealthzWithHttpInfo(string? xRequestID = default)
        {
            Regula.FaceSDK.WebClient.Client.RequestOptions localVarRequestOptions = new Regula.FaceSDK.WebClient.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = Regula.FaceSDK.WebClient.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Regula.FaceSDK.WebClient.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            if (xRequestID != null)
            {
                localVarRequestOptions.HeaderParameters.Add("X-RequestID", Regula.FaceSDK.WebClient.Client.ClientUtils.ParameterToString(xRequestID)); // header parameter
            }


            // make the HTTP request
            var localVarResponse = this.Client.Get<DeviceInfo>("/api/healthz", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("Healthz", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Server healthcheck The &#x60;/api/healthz&#x60; endpoint performs a server health check, providing details such as the application name, license ID, serial number, validity, and product version. &lt;br&gt;&lt;br&gt;Comprehensive information about service diagnostics is available on the [Monitoring page](https://docs.regulaforensics.com/develop/face-sdk/web-service/administration/monitoring/).
        /// </summary>
        /// <exception cref="Regula.FaceSDK.WebClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xRequestID">Request header label. (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of DeviceInfo</returns>
        public async System.Threading.Tasks.Task<DeviceInfo> HealthzAsync(string? xRequestID = default, System.Threading.CancellationToken cancellationToken = default)
        {
            Regula.FaceSDK.WebClient.Client.ApiResponse<DeviceInfo> localVarResponse = await HealthzWithHttpInfoAsync(xRequestID, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Server healthcheck The &#x60;/api/healthz&#x60; endpoint performs a server health check, providing details such as the application name, license ID, serial number, validity, and product version. &lt;br&gt;&lt;br&gt;Comprehensive information about service diagnostics is available on the [Monitoring page](https://docs.regulaforensics.com/develop/face-sdk/web-service/administration/monitoring/).
        /// </summary>
        /// <exception cref="Regula.FaceSDK.WebClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xRequestID">Request header label. (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (DeviceInfo)</returns>
        public async System.Threading.Tasks.Task<Regula.FaceSDK.WebClient.Client.ApiResponse<DeviceInfo>> HealthzWithHttpInfoAsync(string? xRequestID = default, System.Threading.CancellationToken cancellationToken = default)
        {

            Regula.FaceSDK.WebClient.Client.RequestOptions localVarRequestOptions = new Regula.FaceSDK.WebClient.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };


            var localVarContentType = Regula.FaceSDK.WebClient.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Regula.FaceSDK.WebClient.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            if (xRequestID != null)
            {
                localVarRequestOptions.HeaderParameters.Add("X-RequestID", Regula.FaceSDK.WebClient.Client.ClientUtils.ParameterToString(xRequestID)); // header parameter
            }


            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.GetAsync<DeviceInfo>("/api/healthz", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("Healthz", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// License healthcheck The &#x60;/api/readyz&#x60; endpoint checks the license&#39;s health to determine if the application is ready for operation. It validates the license and returns a response indicating whether the license is valid (&#x60;200&#x60;) or invalid (&#x60;400&#x60;).
        /// </summary>
        /// <exception cref="Regula.FaceSDK.WebClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xRequestID">Request header label. (optional)</param>
        /// <returns></returns>
        public void Readyz(string? xRequestID = default)
        {
            ReadyzWithHttpInfo(xRequestID);
        }

        /// <summary>
        /// License healthcheck The &#x60;/api/readyz&#x60; endpoint checks the license&#39;s health to determine if the application is ready for operation. It validates the license and returns a response indicating whether the license is valid (&#x60;200&#x60;) or invalid (&#x60;400&#x60;).
        /// </summary>
        /// <exception cref="Regula.FaceSDK.WebClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xRequestID">Request header label. (optional)</param>
        /// <returns>ApiResponse of Object(void)</returns>
        public Regula.FaceSDK.WebClient.Client.ApiResponse<Object> ReadyzWithHttpInfo(string? xRequestID = default)
        {
            Regula.FaceSDK.WebClient.Client.RequestOptions localVarRequestOptions = new Regula.FaceSDK.WebClient.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
            };

            var localVarContentType = Regula.FaceSDK.WebClient.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Regula.FaceSDK.WebClient.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            if (xRequestID != null)
            {
                localVarRequestOptions.HeaderParameters.Add("X-RequestID", Regula.FaceSDK.WebClient.Client.ClientUtils.ParameterToString(xRequestID)); // header parameter
            }


            // make the HTTP request
            var localVarResponse = this.Client.Get<Object>("/api/readyz", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("Readyz", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// License healthcheck The &#x60;/api/readyz&#x60; endpoint checks the license&#39;s health to determine if the application is ready for operation. It validates the license and returns a response indicating whether the license is valid (&#x60;200&#x60;) or invalid (&#x60;400&#x60;).
        /// </summary>
        /// <exception cref="Regula.FaceSDK.WebClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xRequestID">Request header label. (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of void</returns>
        public async System.Threading.Tasks.Task ReadyzAsync(string? xRequestID = default, System.Threading.CancellationToken cancellationToken = default)
        {
            await ReadyzWithHttpInfoAsync(xRequestID, cancellationToken).ConfigureAwait(false);
        }

        /// <summary>
        /// License healthcheck The &#x60;/api/readyz&#x60; endpoint checks the license&#39;s health to determine if the application is ready for operation. It validates the license and returns a response indicating whether the license is valid (&#x60;200&#x60;) or invalid (&#x60;400&#x60;).
        /// </summary>
        /// <exception cref="Regula.FaceSDK.WebClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xRequestID">Request header label. (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse</returns>
        public async System.Threading.Tasks.Task<Regula.FaceSDK.WebClient.Client.ApiResponse<Object>> ReadyzWithHttpInfoAsync(string? xRequestID = default, System.Threading.CancellationToken cancellationToken = default)
        {

            Regula.FaceSDK.WebClient.Client.RequestOptions localVarRequestOptions = new Regula.FaceSDK.WebClient.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
            };


            var localVarContentType = Regula.FaceSDK.WebClient.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Regula.FaceSDK.WebClient.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            if (xRequestID != null)
            {
                localVarRequestOptions.HeaderParameters.Add("X-RequestID", Regula.FaceSDK.WebClient.Client.ClientUtils.ParameterToString(xRequestID)); // header parameter
            }


            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.GetAsync<Object>("/api/readyz", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("Readyz", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

    }
}
