name: publish nuget package

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup DotNet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '3.1.x'
      - run: dotnet pack src/Regula.FaceSDK.WebClient -c Release -p:PackageVersion=${{github.event.release.name}} -p:Version=${{github.event.release.name}}
      - run: dotnet nuget push src/Regula.FaceSDK.WebClient/bin/Release/Regula.FaceSDK.WebClient.${{github.event.release.name}}.nupkg -k ${{secrets.NUGET_AUTH_TOKEN}} -s https://api.nuget.org/v3/index.json
