name: run smoke test

on:
  pull_request:
    branches:
      - master
      - stable
      - develop

jobs:
  run_smoke_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup DotNet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '6.0.x'
      - run: dotnet build src/Regula.FaceSDK.NetCoreExample -c Release
      - run: ./Regula.FaceSDK.NetCoreExample
        working-directory: src/Regula.FaceSDK.NetCoreExample/bin/Release/net6.0/
        env:
          API_BASE_PATH: "https://faceapi.regulaforensics.com/"
