name: run smoke test

on:
  pull_request:
    branches:
      - master
      - develop
      - stable

jobs:
  run_smoke_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'
      - run: dotnet build src/Regula.FaceSDK.NetCoreExample -c Release
      - working-directory: src/Regula.FaceSDK.NetCoreExample/bin/Release/net6.0/
        run: ./Regula.FaceSDK.NetCoreExample
        env:
          API_BASE_PATH: "https://faceapi.regulaforensics.com/"
